### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dhanish89** [klaytn/klaytn-dex-frontend#42]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by dhanish89** [comment]
UI/UX is good and runs normally
but can't vote
even though there is a balance
![image](https://user-images.githubusercontent.com/113315212/204783242-074991be-9e4a-42de-9598-c541e3d6955a.png)

**Comment by Homer-Klaytn** [comment]
Hello @dhanish89  In order to vote you should have enough KDEX tokens before the proposal creation. Your voting power is calculated based on number of tokens you hold at the time(Block) of proposal creation. You can only vote for the latest proposals that were created after you've accumulated KDEX tokens. To accumulate DEX tokens depends on how much you stake , which liquidity pool and number of days! 

Thank you and please reach out if you have any additional questions
