### ISSUE TITLE
Can't Vote

### ISSUE THREAD

**Issue by Cryptobusy8** [klaytn/klaytn-dex-frontend#96]
**Describe the bug**
Voting power is illegible or has no amount

**How to reproduce**
-

**Expected behavior**
-

**Attachments**
![Screenshot_20221130-222848_Browser Alpha](https://user-images.githubusercontent.com/100507227/204839735-f8cc7783-11ef-42f0-9deb-ff48b3abb26a.jpg)

**Environment (please complete the following information)**
 - Samsung A52 Android 12 version
 - Wallet and its version used [Alpha Yandex browser - Metamask Extention]

**Additional context**
-

**Comment by Homer-Klaytn** [comment]
Hello @Cryptobusy8 In order to vote you should have enough KDEX tokens before the proposal creation. Your voting power is calculated based on number of tokens you hold at the time(Block) of proposal creation. You can only vote for the latest proposals that were created after you've accumulated KDEX tokens. To accumulate DEX tokens depends on how much you stake , which liquidity pool and number of days! 

Thank you and please reach out if you have any additional questions
